name: Main
on: [push, pull_request]
jobs:
  Pet_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install modules
        run: npm install

      - name: Run test
        run: npm test
